### PR TITLE
Cron expression will now raise ValueError when expression values are …

### PR DESCRIPTION
**Pull request by ofirule**
…out of range (#189)

### CODE REVIEW

**Comment by ofirule** [comment]
Hi @agronholm please have a look, I think this is a nice fix/feature

**Comment by agronholm** [comment]
Yes, I will take a closer look during the weekend.

**Comment by agronholm** [comment]
While you wait, please fix the long lines (>99 cols) in your PR.

**Comment by agronholm** [comment]
While I agree that this should be done, I'm not sure this is the way after looking at the implementation. I was almost sure I had something before for checking that the value is within the limits. At any rate, the tests should be done using py.test's parametrization feature. But there's no rush, I might even create my own patch instead of merging this one.

**Comment by agronholm** [comment]
I ended up fixing this my own way. Thanks for your effort though.

**Comment by ofirule** [comment]
Great, I will definitely use it

**Pull request closed without merging**
