### PR TITLE
added PySide2 support

### PR DESCRIPTION
**Pull request by abood91**
Added support to PySide2, PySide is outdated and does not support higher versions of python

### CODE REVIEW

**Comment by abood91** [comment]
Any progress on this @agronholm  ?

**Comment by agronholm** [comment]
Impatient, are we? Well, I see no downsides in this so I can just go ahead and merge it.

**Comment by agronholm** [comment]
I hadn't done this myself because the future of Qt support within apscheduler (4.x onwards) is yet unclear.

**Comment by abood91** [comment]
> 
> 
> Impatient, are we? Well, I see no downsides in this so I can just go ahead and merge it.

Haha :D sorry to bother. I needed the merge in order to continue my work :)

**Pull request merged**
