### PR TITLE
Wakeup worker when there are resources freed up

### PR DESCRIPTION
**Pull request by mavahedinia**
Related to the bug reported on [Issue#881](https://github.com/agronholm/apscheduler/issues/881).

### CODE REVIEW

**Comment by mavahedinia** [comment]
I would appreciate if you can help me understand why some tests are failing. @agronholm

**Comment by agronholm** [comment]
Would it be possible for you to add a regression test for this?
As for the other tests failing, I can probably take a look later.

**Comment by agronholm** [comment]
Oh, and also add a changelog entry (credit yourself too).

**Comment by mavahedinia** [comment]
I will look into writing tests over the weekend. Thanks for your fast response!

**Comment by agronholm** [comment]
Any progress on those tests?

**Comment by mavahedinia** [comment]
Sorry man, I am so busy with moving that haven't had any chance to look at it.

**Comment by agronholm** [comment]
One issue I have with this PR is that it needlessly wakes up the job processor whenever a job is released, not just when the processor was previously at capacity. Could you fix that?

**Comment by agronholm** [comment]
But if you're still busy with IRL stuff, let me know and I'll look into fixing it and writing tests.

**Comment by agronholm** [comment]
I've added the test and changelog entry on your behalf. Thank you for the contribution!

**Pull request merged**
