### PR TITLE
Allow Job to be weak-referenced

### PR DESCRIPTION
**Pull request by bharel**
ATM, you can't weakref a job.
If a function in a job needs the job, it will cause circular reference.
Adding a `__weakref__` field will solve it.

### CODE REVIEW

**Comment by bharel** [comment]
Master is failing. None of the failures have anything to do with my PR.

**Comment by agronholm** [comment]
What is the reason for this PR?

**Comment by agronholm** [comment]
Master is a mess because I'm building APScheduler 4.0 in it and most of the architecture is not in place yet.

**Comment by agronholm** [comment]
You're not supposed to store `Job` objects for long periods yourself. Store job ids instead and use them to remove the jobs from the scheduler when necessary.

**Comment by agronholm** [comment]
Can't you just delete the `job` variable after you call `remove()`?

**Comment by bharel** [comment]
> You're not supposed to store `Job` objects for long periods yourself. Store job ids instead and use them to remove the jobs from the scheduler when necessary.

The [https://apscheduler.readthedocs.io/en/stable/userguide.html#removing-jobs](user guide) suggests otherwise 🤷‍♂️ 

> Can't you just delete the `job` variable after you call `remove()`?

You're right, I can probably delete it from the closure using `nonlocal`, or by passing it as an argument but these are mostly workarounds for a field that is supposed to exist on almost every custom python object.

**Comment by bharel** [comment]
Actually, if the argument is saved separately inside the job object, I won't be able to `del` it.
Also, if the job doesn't run, it won't be able to clear it's own variable from the closure, regardless of `nonlocal`, so the workaround isn't too promising 😢

**Comment by agronholm** [comment]
The best I can do here is merge this into the v3.x branch. Master is still too much in the flux and the current `Job` class may be radically altered there or go away completely.

**Comment by bharel** [comment]
Works for me 🤷 

Why will there be no job class? I think it's a fair design.

**Comment by agronholm** [comment]
In APScheduler 4.0, jobs will be split into three parts:

1. Task definitions (named; contains the callable object along with several configuration parameters)
1. Schedules (always tied to task definitions)
1. Jobs (created by executors; always tied to task definitions but only optionally to schedules)

The name "job" on the last line is subject to change if deemed necessary.

**Comment by agronholm** [comment]
I can make this change in 3.x but you need to rebase your code against the 3.x branch.

**Pull request closed without merging**
