### PR TITLE
Job._get_run_times() may fall into endless loop while next_run_time equals to now

### PR DESCRIPTION
**Pull request by baijinping**
I made some changes.Please review.

### CODE REVIEW

**Comment by agronholm** [comment]
Thanks for the test case. I have quite a bit of trouble understanding the situation, but I'm definitely looking into this.

**Comment by agronholm** [comment]
It seems like there are some definitions that need to be made here. What happens if the clock is set backwards? That's the only plausible case for `previous_fire_time` and `now` being exactly the same.

**Comment by agronholm** [comment]
Can you rationalize your patch? It's not like `now` will stay the same value on consecutive runs. Help me understand the problem.

**Comment by baijinping** [comment]
The problem is similar to the example below.
After running it, there is nothing output and CPU is busy.

---

```
import time
from datetime import datetime
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger


scheduler = BackgroundScheduler()
scheduler.start()


def task():
    print 'run task at ', datetime.now()

trigger = CronTrigger(second='*')
scheduler.add_job(task, trigger=trigger)

time.sleep(99)
```

**Comment by agronholm** [comment]
That's not what happens here. This is what I get:
```
$ python bleh.py 
run task at  2016-04-26 04:12:02.000581
run task at  2016-04-26 04:12:03.001185
run task at  2016-04-26 04:12:04.004014
run task at  2016-04-26 04:12:05.004050
run task at  2016-04-26 04:12:06.000955
run task at  2016-04-26 04:12:07.000957
run task at  2016-04-26 04:12:08.001065
run task at  2016-04-26 04:12:09.001224
run task at  2016-04-26 04:12:10.001441
run task at  2016-04-26 04:12:11.002440
run task at  2016-04-26 04:12:12.002491
run task at  2016-04-26 04:12:13.000839
run task at  2016-04-26 04:12:14.001759
run task at  2016-04-26 04:12:15.001421
run task at  2016-04-26 04:12:16.000711
run task at  2016-04-26 04:12:17.000702
run task at  2016-04-26 04:12:18.000785
```

**Comment by agronholm** [comment]
By the way, when you print datetime.now(), does it not display microseconds?

**Comment by baijinping** [comment]
Yes.This is what I get after I modify _get_next_fire_time():
run task at  2016-04-26 09:16:04
run task at  2016-04-26 09:16:05.001000
run task at  2016-04-26 09:16:06.002000
run task at  2016-04-26 09:16:07.001000
run task at  2016-04-26 09:16:08.002000

**Comment by agronholm** [comment]
What OS and Python version are you running? You should be getting arbitrary numbers as microseconds, not something as clean as 001000 or 002000.

**Comment by agronholm** [comment]
Try just running this script for a few seconds:
```python
from datetime import datetime

while True:
    print(datetime.now())
```
and tell me what it prints.

**Comment by baijinping** [comment]
I run the code at Windows 7 and Python 2.7.11.

**Comment by baijinping** [comment]
The output is like:
2016-04-26 09:26:31.730000
2016-04-26 09:26:31.730000
(repeat few times...)
2016-04-26 09:26:31.731000
2016-04-26 09:26:31.731000
(repeat few times...)
2016-04-26 09:26:31.732000
(repeat few times...)
2016-04-26 09:26:31.733000
(repeat few times...)

**Comment by agronholm** [comment]
I see -- your computer is not capable of microsecond precision in measuring time. It can only produce millisecond precision timestamps.

**Comment by agronholm** [comment]
That still doesn't explain why your script would go into an endless loop trying to compute the next run time. The code already adds one microsecond to previous_fire_time to prevent that from happening. Can you verify that adding one microsecond to a datetime works as expected?

**Comment by baijinping** [comment]
Run this script will go into an endless loop in my computer.

```
import time
import pytz
from datetime import datetime
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.cron import CronTrigger


scheduler = BackgroundScheduler()
scheduler.start()


def task():
    print 'run task at ', datetime.now()

trigger = CronTrigger(second='*')
job = scheduler.add_job(task, trigger=trigger)

now = pytz.UTC.localize(datetime.now())

# block here
job._get_run_times(now)

time.sleep(99)
```

**Comment by baijinping** [comment]
```
def get_next_fire_time(self, previous_fire_time, now):
        if previous_fire_time:
            start_date = min(now, previous_fire_time + timedelta(microseconds=1))
        else:
            start_date = max(now, self.start_date) if self.start_date else now
......
```
If "previous_fire_time" equals now, start_date will still be set "now" because of the "min".

**Comment by agronholm** [comment]
I'll take another look at this tomorrow, but for the record, your latest script works fine here.

**Comment by baijinping** [comment]
OK. I think the reason why go into an endless loop we have found -- Python can't get accurate microsecond at Windows.

**Comment by agronholm** [comment]
I have a Windows machine too and it has no problem getting timestamps with microsecond accuracy.

**Comment by baijinping** [comment]
How you get timestamps with microsecond accuracy on Windows?
datetime.now() or time.time()?

**Comment by agronholm** [comment]
`datetime.now()` works for me.

**Comment by agronholm** [comment]
The test scripts so far have reproduced the problem for you based solely on your computer hardware. But can you write a script for me that produces this infinite loop based on a fixed value of "now"? That would let me debug the issue locally.

**Comment by baijinping** [comment]
I tried run datetime.now() on many WIndows machine, and got the same result(microsecond value like 345000).
I google "python datetime microsecond windows" and found some people get the same datetime.now() result like me.

**Comment by baijinping** [comment]
In order to reproduce at Linux, I change apscheduler/schedulers/base.py, add some code:

```
......
from threading import RLock

from datetime import datetime as datetime_build_in
class datetime(datetime_build_in):

    @classmethod
    def now(cls, tz=None):
        now = datetime_build_in.now(tz=tz)
        old_micro = now.microsecond
        # change precision from 1000 to 1000000
        # will increase endless loop happen probability
        precision = 1000
        new_micro = old_micro - old_micro % precision
        now = now.replace(microsecond=new_micro)
        return now

from logging import getLogger
import sys
......
```

**Comment by baijinping** [comment]
Hope to be helpful.

**Comment by agronholm** [comment]
Hey, could you test if it makes any difference if you change line 139 in `cron/__init__.py` from `microseconds=1` to `microseconds=1000`? Also, do you get the expected result if you add `timedelta(microseconds=1)` to a datetime?

**Comment by baijinping** [comment]
The problem also exists after I change ```microseconds=1``` to ```microseconds=1000```.
I got ```2016-05-05 15:57:10 127001``` after I add ```timedelta(microseconds=1)``` to ```2016-05-05 15:57:10 127000```.

**Comment by agronholm** [comment]
No matter how many times I try, even with the modified datetime class you pasted, I cannot reproduce this problem.

**Comment by agronholm** [comment]
The way I see it, the only way I could understand why this happens is if you give me some way to cause the infinite loop without relying on the hardware clock. Surely there is some datetime value you can directly input that will cause the infinite loop?

**Comment by baijinping** [comment]
Maybe the timezone is the reason.

**Comment by agronholm** [comment]
I don't see how that could be, but maybe you can try with different timezones then to confirm your theory?

**Comment by baijinping** [comment]
When scheduler add a job, the job's attribute "next_run_time" will set to now.
```
# Calculate the next run time if there is none defined
if not hasattr(job, 'next_run_time'):
    now = datetime.now(self.timezone)
    replacements['next_run_time'] = job.trigger.get_next_fire_time(None, now)
```

And the microsecond value in job.next_run_time equals to zero(after ```datetime_ceil()```).

Then call ```_get_run_times(now)```, which now.microsecond may equals to zero.

If there is less then one second between call ```_real_add_job``` and ```_get_run_times```, the arguments sent into ```_get_next_fire_time``` will be equals(previous_fire_time == now).

In this situation, the code below can't help.
```
if previous_fire_time:
    start_date = min(now, previous_fire_time + timedelta(microseconds=1))
else:
    start_date = max(now, self.start_date) if self.start_date else now
```

Then return the same date time value.
The endless loop happen now.

**Comment by agronholm** [comment]
Your logic is a bit flawed. If `now` and `previous_fire_time` are exactly the same, `start_date` would end up `now` + 1 microsecond.

**Comment by agronholm** [comment]
I also don't understand why the microsecond being zero would have any significance.

**Comment by agronholm** [comment]
Can you construct a Job and a datetime value for `now` in such a way that calling job._get_run_times(now) would end up in an infinite loop?

**Comment by agronholm** [comment]
Never mind, I managed to do that on my own now.

**Comment by baijinping** [comment]
The new test may show the problem in you computer.

**Comment by agronholm** [comment]
I have fixed this in 21aa9a944247f4e05dfc91fc8dfed23b5d2b6d89 and credited you in the version history. I did not directly use your patch except for one of the tests. Switching from max() to min() in the case when previous_fire_time is `None` would have caused some fire times to be missed.

**Pull request closed without merging**
