### PR TITLE
Update test_triggers.py

### PR DESCRIPTION
**Pull request by backbord**
Test crossing both dst change and midnight at the same time.

### CODE REVIEW

**Comment by agronholm** [comment]
The official repository is still at bitbucket; this was left here because I intend to eventually complete the migration. That said, what is the motivation for this? Would this test fail in the master or waht?

**Comment by backbord** [comment]
Hi, yes, the test fails in 3.0.5.
Sorry, I wasn't aware of the move to BitBucket. Should I re-commit the pull-request at BitBucket?

**Comment by agronholm** [comment]
The repository hasn't moved to Bitbucket, it's always been here. This github repo exists because I intended to migrate the code here from BB. I had trouble with issue import however, which is why things were left in this state.

If there's a bug in 3.0.5, would you mind fixing it too?

**Comment by backbord** [comment]
I'm relatively new to github and the apscheduler internals, but sure, I'll try my best.
I didn't find it in the first 30 minutes after stumbling upon the behaviour, so it might take a bit.

**Comment by agronholm** [comment]
Looking at your tests, you're giving 08:01 (non-DST) as a start time. That corresponds to 09:01 with DST so why would you expect the result to be 08:00 (DST)?

**Comment by backbord** [comment]
It's the day before. 2016-03-26T08:01 CET --> next trigger should be 2016-03-27T08:00 CEST but I get 2016-03-27T09:00

I think this can be fixed by replacing the last two lines in _set_field_value by
        return self.timezone.localize(datetime(**values))

because the difference = datetime(**values) - dateval.replace(tzinfo=None) builds a naive datetime (which should be in CEST) and subtracts from it a datetime in CET. The difference appears to be wrong.

Also: the first check in test_dst_change seems off:
I looked at https://www.timeanddate.com/time/change/usa/new-york?year=2013
        datetime_edt = eastern.localize(datetime(2013, **11, 3, 1, 5**), is_dst=**True**)
        correct_next_date = eastern.localize(datetime(2013, **11, 3, 1, 30**), is_dst=**True**)
        assert str(trigger.get_next_fire_time(None, datetime_edt)) == str(correct_next_date)

I reckon that you meant two write something in the gist of
        datetime_edt = eastern.localize(datetime(2013, **3, 10, 1, 35**), is_dst=**False**)
        correct_next_date = eastern.localize(datetime(2013, **3, 10, 3, 0**), is_dst=**True**)
        assert str(trigger.get_next_fire_time(None, datetime_edt)) == str(correct_next_date)

What do you think?

**Comment by backbord** [comment]
I'm not sure what to do. How about I'll put the change from _this_ pull request together with the changes from my previous comment into a single new pull request?

**Comment by agronholm** [comment]
I will not accept any PR that breaks the build. So either raise an issue at Bitbucket or make a PR there with a patch.

**Comment by agronholm** [comment]
The test was also in the wrong class. Since this concerns the Cron trigger, the test should be inside TestCronTrigger.

**Comment by backbord** [comment]
sorry for the hassle. I'll just file an issue.

**Comment by agronholm** [comment]
Before you do that, switch to a locale based zone. CET will never switch to DST (CEST).

**Comment by backbord** [comment]
That does not sound right to me. CET and Europe/Berlin are virtually the same
https://github.com/newvem/pytz/blob/master/pytz/zoneinfo/CET.py
https://github.com/newvem/pytz/blob/master/pytz/zoneinfo/Europe/Berlin.py

Just tested it. No, it does not help in this case. I'll file a bug report.

Have a nice easter, keep up the good work and thanks for the great tool!
I really appreciate it!

**Comment by backbord** [comment]
... and sorry for my hectic pull request. I stressed out after our customers reported data arriving an hour late. I did not intend to cause unnecessary work at your end.

Again, thanks for the great tool!

**Comment by agronholm** [comment]
I've left some comments at bitbucket. Let's finish the discussion there.

**Pull request closed without merging**
