### PR TITLE
Fixed textual referenced bound methods issue on persistent job stores #466

### PR DESCRIPTION
**Pull request by spengjie**
For issue #466.

### CODE REVIEW

**Comment by agronholm** [comment]
Please also add a test that fails without this fix.

**Comment by agronholm** [comment]
Did you notice that the test suite does not pass with this patch?

**Comment by spengjie** [comment]
I'm on holiday, just got a chance to read the GitHub notifications. I‘ve tested locally without any issues. tox always stuck in PyQt5 installation in my local environment. So I didn't check the tox result. This is not right. I just fixed the tox problem, will check the test failures and add new test cases.

**Comment by agronholm** [comment]
Looking good. The py3.5 test collection failure is probably just caused by test deps no longer supporting 3.5 because it has reached EOL.

**Comment by spengjie** [comment]
In my local environment, tox always got InvocationError for all Python versions after I ran tox against py35 only. I deleted all the temp files and restored the code changes to restore the environment, but there's nothing changed. This is a very strange issue. I will continue the troubleshooting tomorrow.

**Comment by agronholm** [comment]
Running pytest without tox works fine, but `tox -e py35` crashes with the same error as on Travis.

**Comment by agronholm** [comment]
I've fixed the problem in the 3.x branch. Please rebase your code (or merge the latest changes)

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
