### PR TITLE
fix: Set CRON trigger fields

### LINKED ISSUE #923: `'CronTrigger' object has no attribute 'year'` when try to pause schedule
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

4.0.0a5

### What happened?

Hi! When I try to pause schedule of a task, created with cron trigger, I'm getting following error.
Do you have any advice or workaround maybe for this kind of event? Thanks!

Environment:
```
python = "3.11.4"
apscheduler = "4.0.0a5"
sqlalchemy = "2.0.30"
asyncpg = "0.29.0"

```

The error itself:
```
Traceback (most recent call last):
  File "/home/krosenmann/sources/apscheduler-minimal-example/executor_test.py", line 26, in main
    await scheduler.pause_schedule(id='this-is-the-end')
  File "/home/krosenmann/.cache/pypoetry/virtualenvs/apscheduler-minimal-example-RlZethiB-py3.11/lib/python3.11/site-packages/apscheduler/_schedulers/async_.py", line 538, in pause_schedule
    await self.data_store.add_schedule(
  File "/home/krosenmann/.cache/pypoetry/virtualenvs/apscheduler-minimal-example-RlZethiB-py3.11/lib/python3.11/site-packages/apscheduler/datastores/sqlalchemy.py", line 504, in add_schedule
    schedule.marshal(self.serializer)
  File "/home/krosenmann/.cache/pypoetry/virtualenvs/apscheduler-minimal-example-RlZethiB-py3.11/lib/python3.11/site-packages/apscheduler/_structures.py", line 143, in marshal
    marshalled = attrs.asdict(self, value_serializer=serialize)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/krosenmann/.cache/pypoetry/virtualenvs/apscheduler-minimal-example-RlZethiB-py3.11/lib/python3.11/site-packages/attr/_next_gen.py", line 211, in asdict
    return _asdict(
           ^^^^^^^^
  File "/home/krosenmann/.cache/pypoetry/virtualenvs/apscheduler-minimal-example-RlZethiB-py3.11/lib/python3.11/site-packages/attr/_funcs.py", line 65, in asdict
    rv[a.name] = asdict(
                 ^^^^^^^
  File "/home/krosenmann/.cache/pypoetry/virtualenvs/apscheduler-minimal-example-RlZethiB-py3.11/lib/python3.11/site-packages/attr/_funcs.py", line 56, in asdict
    v = getattr(inst, a.name)
        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CronTrigger' object has no attribute 'year'

```

### How can we reproduce the bug?

Following code reproduces bug
```py
import asyncio

from apscheduler.datastores.sqlalchemy import SQLAlchemyDataStore
from apscheduler.serializers.json import JSONSerializer

from apscheduler import AsyncScheduler
from apscheduler.triggers.cron import CronTrigger


async def dummy_task():
    await asyncio.sleep(1)
    print("Banana!")


async def main():
    data_store = SQLAlchemyDataStore(
        engine_or_url="postgresql+asyncpg://<user>:<password>@127.0.0.1:15433/task_scheduler_data_store",
        serializer=JSONSerializer()
    )
    async with AsyncScheduler(data_store=data_store) as scheduler:
        # Add schedules, configure tasks here
        task = await scheduler.configure_task(dummy_task)

        schedule = await scheduler.add_schedule(task, id='this-is-the-end',
                                                trigger=CronTrigger.from_crontab('* * * * *'))
        await scheduler.pause_schedule(id='this-is-the-end')

asyncio.run(main())
```

### PR DESCRIPTION
**Pull request by WillDaSilva**
## Changes

Fixes #923

## Checklist

If this is a user-facing code change, like a bugfix or a new feature, please ensure that
you've fulfilled the following conditions (where applicable):

- [ ] You've added tests (in `tests/`) added which would fail without your patch
- [ ] You've updated the documentation (in `docs/`, in case of behavior changes or new
features)
- [ ] You've added a new changelog entry (in `docs/versionhistory.rst`).

If this is a trivial change, like a typo fix or a code reformatting, then you can ignore
these instructions.

### Updating the changelog

If there are no entries after the last release, use `**UNRELEASED**` as the version.
If, say, your patch fixes issue #999, the entry should look like this:

`* Fix big bad boo-boo in the async scheduler (#999
<https://github.com/agronholm/apscheduler/issues/999>_; PR by @yourgithubaccount)`

If there's no issue linked, just link to your pull request instead by updating the
changelog after you've created the PR.

### CODE REVIEW

**Comment by agronholm** [comment]
The proper fix would be to override `__init__()` to accept the individual fields, and call `__attrs_init__()` to fill in the fields we want to keep, and then fill in the `_fields` attribute. A test that fails without the fix would also be required.

**Comment by WillDaSilva** [comment]
> A test that fails without the fix would also be required.

Yup. I plan to add one before I mark this as ready for review.

> fill in the fields we want to keep

@agronholm I'm not sure what you mean by this. Don't we want to keep all of the fields? Specifically, that is:
- `year`
- `month`
- `day`
- `week`
- `day_of_week`
- `hour`
- `minute`
- `second`
- `start_time`
- `end_time`
- `timezone`
- `last_fire_time`

If you feel you know how to fix it, and that fixing it yourself would be easier than helping me fix it, feel free to take it away. Otherwise I'm happy to see this through. Whatever's easiest for you.

**Comment by agronholm** [comment]
The initializer parameters from `year` to `second` were only supposed to be used to fill out the appropriate fields, and should not be stored in the instance. That this happened was an artifact of the class being transformed into an `attrs` class. Before I started using `attrs` in APScheduler, I had intended these to be InitVars when the trigger class was going to be a data class, but attrs does not have such a feature. Instead, its docs recommend overriding `__init__()`. I'll see about doing this tomorrow.

**Comment by agronholm** [comment]
Closing in favor of commit 0240dce0.

**Pull request closed without merging**
