### PR TITLE
Issue#138: EVENT_JOB_BEFORE_REMOVE callback feature needed

### PR DESCRIPTION
**Pull request by saadqc**
Hi @agronholm 
I have added callback for EVENT_JOB_BEFORE_REMOVE. Kindly review the PR and let me know
if it can be improved.

Thanks,
Saad

### CODE REVIEW

**Comment by saadqc** [comment]
@agronholm : I am not sure why it is not been able to connect to rethinkdb. 
See https://travis-ci.org/agronholm/apscheduler/jobs/127494324
Although all tests passed in other python languages 
https://travis-ci.org/agronholm/apscheduler/builds/127494322

Could you please look into this?

**Comment by agronholm** [comment]
I have no clue why it would specifically fail on 3.3 and not others. I saw this problem locally but upgrading both the docker image and the driver solved it. But Travis containers are supposed to be blank slates so I have no idea why it would get old versions of either.

**Comment by saadqc** [comment]
@agronholm its a bug in rethink db.
I have created and fixed the issue. PR is up and they are looking forward to merge the change.

Issue: https://github.com/rethinkdb/rethinkdb/issues/5742#issuecomment-216576073

PR: https://github.com/rethinkdb/rethinkdb/pull/5743

If the change is looks good, is there any chance you can merge this after code review?

**Comment by agronholm** [comment]
The code and tests look fine but I have no decided yet whether I *want* this change. I will review your use case in depth and make my decision then.

**Comment by saadqc** [comment]
@agronholm : sure, our app is in production. And the endpoint is pretty slow due to no filtering support. So, i am going to use code from my branch for now.

**Comment by agronholm** [comment]
I've disabled Python 3.3 testing until the RethinkDB issues can be sorted out.

**Comment by saadqc** [comment]
@agronholm : yeah. btw, they merged my change. You can re-install rethink on travis using the latest code. (branch-> next). https://github.com/rethinkdb/rethinkdb

Hopefully this will pass all tests. :-)

**Comment by agronholm** [comment]
I still haven't fully reviewed your use case. I will not include this in the next release anyway. It will be in 3.3 at the earliest **IF** I decide to include it.

**Comment by saadqc** [comment]
@agronholm sure.

**Comment by agronholm** [comment]
Closing as this need is better served by a job tagging system.

**Comment by saadqc** [comment]
@agronholm Is that added in new version?

**Comment by agronholm** [comment]
Not yet, but it is something I've been thinking about for a while.

**Comment by saadqc** [comment]
@agronholm Right. I am creating an issue regarding multiple times job execution on uwsgi flask server. 
http://stackoverflow.com/questions/16053364/make-sure-only-one-worker-launches-the-apscheduler-event-in-a-pyramid-web-app-ru

http://stackoverflow.com/questions/24352634/would-starting-apscheduler-in-a-uwsgi-app-end-up-with-one-scheduler-for-each-wor

**Pull request closed without merging**
