### PR TITLE
Jobstore with SQLite3

### PR DESCRIPTION
**Pull request by pascalziegler**
To avoid the dependency of sqlalchemy I wrote a jobstore with sqlite3. This could be used in https://github.com/borgbase/vorta/pull/377

### CODE REVIEW

**Comment by agronholm** [comment]
I don't see why I should add a redundant job store just because someone doesn't want to install SQLAlchemy. Can you explain?

**Comment by pascalziegler** [comment]
Well SQLite3 is contained in the standard python installation, so no additional packages are needed to use this jobstore. And I think there are more projects like Vorta which wants to keep the amount of dependencies small.

**Comment by pascalziegler** [comment]
Do you know why the Error `fixture 'event_loop' not found` occurs? That Error was thrown even before I started to write that jobstore. I thought it was a problem with my local machine, but the last commit on master also failed on Travis.

**Comment by agronholm** [comment]
> Well SQLite3 is contained in the standard python installation, so no additional packages are needed to use this jobstore.

APScheduler itself is not part of the standard library which kinda defeats that argument. Also, any new job stores I take on would increase the burden of maintenance and I don't see the benefit.

> And I think there are more projects like Vorta which wants to keep the amount of dependencies small.

I've never heard of this. Sorry to sound callous but why should I care?

**Pull request closed without merging**
