### PR TITLE
Allow Job to be weak-referenced

### PR DESCRIPTION
**Pull request by bharel**
Reupload of PR GH-442 after a rebase.

### CODE REVIEW

**Comment by agronholm** [comment]
For future reference, you could've just rebased the code in the previous PR.

**Comment by bharel** [comment]
Got stuck with lots of conflicts for some reason

**Comment by agronholm** [comment]
The CI run is failing due to flake8 errors. If you want to test locally, you can start the necessary services with `docker-compose up -d` in the project directory and then run `tox`.

**Comment by agronholm** [comment]
Your test relies on a reference counting garbage collector, and because pypy does not have one, the test fails. The suggested fix is to call `gc.collect()` at least once. I suggest you test this locally on pypy until it works.

**Comment by bharel** [comment]
I thought of calling `gc.collect(1)`, just read about pypy's [garbage collector](https://doc.pypy.org/en/latest/cpython_differences.html#differences-related-to-garbage-collection-strategies). To be honest, I didn't think about that scenario. You learn a new thing every day :-)

I'm installing docker in the background for the tests.

**Comment by agronholm** [comment]
Thanks!

**Pull request merged**
