### PR TITLE
bugfix: the method inherited from base class can not be executed by p…

### PR DESCRIPTION
**Pull request by yj97595077**
Issue: https://github.com/agronholm/apscheduler/issues/366

### CODE REVIEW

**Comment by agronholm** [comment]
Please add a test that would fail without this fix.

**Comment by yj97595077** [comment]
> Please add a test that would fail without this fix.

OK, I try to add the testcase.

**Comment by yj97595077** [comment]
> You know that you can use `tox` to run the tests locally, right? You don't have to rely on Travis for that.

Sorry about that. I will use `tox` to run the tests on my computer before pushing the commits from now on.

**Comment by agronholm** [comment]
Thanks!

**Comment by agronholm** [comment]
@yj97595077 I have to ask: why did you make the test so it is skipped on Python 3.2 and above? The reason does not make any sense either.

**Pull request merged**
