### PR TITLE
Implement issue #297 - Passing the scheduled start time to jobs

### PR DESCRIPTION
**Pull request by anon-john**
This PR implements the feature request from #297. Proposed changes were tested against py36, py37, py27 and flake8 with memjobstore and sqlalchemyjobstore stores. At the moment, unfortunately, I'm not able to test with mongo/redis/zookeeper/rethinkdb.

### CODE REVIEW

**Comment by anon-john** [comment]
It looks, that a single test (test_job_provide_scheduled_run_time) fails in travis. Surprisingly, running locally is OK. Any ideas/suggestions?

**Comment by anon-john** [comment]
I executed the following to verify, that there are no missing changes in the branch of this PR:
```
git clone https://github.com/anon-john/apscheduler.git
cd apscheduler/
git checkout provide_scheduled_run_time
docker-compose up

# in a new session
python3.6 -m venv venv
source venv/bin/activate
pip install pytest
cd apscheduler/ # i.e. run against the 'provide_scheduled_run_time' branch
tox
```
With the above method, all tests run fine (i.e. there are no failures). The venv-related steps  are meant to provide modern pytest. Output of pip freeze is the following:
```
atomicwrites==1.3.0
attrs==19.1.0
importlib-metadata==0.18
more-itertools==7.1.0
packaging==19.0
pkg-resources==0.0.0
pluggy==0.12.0
py==1.8.0
pyparsing==2.4.0
pytest==5.0.0
six==1.12.0
wcwidth==0.1.7
zipp==0.5.1
```

**Comment by agronholm** [comment]
I've hatched a more ambitious plan to implement this in APScheduler 4.0. I plan to pass the entire (immutable) job object to the target function.

Do you have Docker installed? The included docker-compose configuration provides an easy way to launch the various databases as containers simply by doing `docker-compose up`.

**Comment by agronholm** [comment]
The problem with the tests does not seem to be related to the job stores though.

**Comment by anon-john** [comment]
> I've hatched a more ambitious plan to implement this in APScheduler 4.0. I plan to pass the entire (immutable) job object to the target function.

do you plan to have another minor release before this (i.e. any chance to have the functionality of this PR before 4.0 is out)? 

One argument to put this in now is that it seems to me the logic you propose (passing of the immutable Job object) could be implemented based on this PR - rename the provide_scheduled_run_time add_job parameter, rename the scheduled_run_time func parameter and pass the Job object instead of the scheduled time to func (do I miss something here? apologies, if I'm wrong, this codebase is rather  new to me).

> Do you have Docker installed? The included docker-compose configuration provides an easy way to launch the various databases as containers simply by doing `docker-compose up`.

yes, tests I mentioned in the later comment ( https://github.com/agronholm/apscheduler/pull/380#issuecomment-507392611 ) were done with a complete setup (i.e. all dbs were set via docker-compose, no modifications were done to test_jobstores.py). 

> The problem with the tests does not seem to be related to the job stores though.

that was also my impression. I checked, that proposed PR is based on current master (it is). I've also tried merging it into the travistest branch, tests still run fine. Observed travis failures are even more surprising, if you note, that the problematic function is based on the test_add_live_job function, i.e. the call mechanics are identicall. The only non-trivial difference is in job function definition - lambda (test_add_live_job) versus local def (new test function). Should I make this function global and see if it helps (i.e. maybe this is some weird pickling related issue)? Anyway, please let me know if I could be of any more help here.

**Comment by agronholm** [comment]
I ran the suite and the tests also fail for me locally, though not at the same point as on Travis. I can take a closer look later today.

I will definitely examine this PR when writing the job passing functionality, regardless of whether I choose to merge it.

**Comment by richwifunds** [comment]
Getting the scheduled start time would be really helpful to a project I'm working on. We're using apscheduler to send jobs to a message broker rather than running the job directly. So we need to implement functionality like "misfire grace time" differently since a message can sit in the queue if there is no available consumer. We can do this by subtracting any time already passed since the scheduled run time from the misfire grace time and using that as the "time to expire" property of the message.

**Comment by agronholm** [comment]
I plan to rearchitect APScheduler in a big way so that not only the start time but various other bits of information are (optinally) passed to the job.

**Comment by anon-john** [comment]
Any news on this?

**Comment by agronholm** [comment]
Yes, see the previous comment.

**Comment by anon-john** [comment]
OK, so if I understand correctly - this won't be merged into 3.x series, this functionality should be available in 4.x, right? If so - is there any (rough) ETA on this?

**Comment by agronholm** [comment]
I'm hoping to get this done before the end of August.

**Comment by agronholm** [comment]
Closing since this will be implemented differently in 4.0.

**Pull request closed without merging**
